### ISSUE TITLE
favicon, meta data 변경, og 태그 변경

### ISSUE THREAD

**Issue by SeungrokYoon** [wanted-pre-onboarding-team-12th-7/pre-onboarding-12th-2-7#10]
#  Todo
수정해야 하는 파일은 `public/index.html`
- [ ] favicon 아이콘 변경하기 
- [ ] 프로젝트 타이틀 변경하기 
- [ ] og 메타태그 변경 => 프로젝트 배포 링크의 미리보기, 설명, 이미지를 변경할 수 있음
