### ISSUE TITLE
README.md 작성

### ISSUE THREAD

**Issue by SeungrokYoon** [wanted-pre-onboarding-team-12th-7/pre-onboarding-12th-2-7#13]
# Todo
- [ ] 다른 팀들의 1주차 과제 README 문서를 보면서 좋았던 점을 벤치마킹하여  이전 템플릿을 기준으로 README개선 아이디어 디스코드에 제안하기
- [ ] README 작성
- [ ] 링크 제대로 동작하는지 확인
- [ ] 컨벤션 레포지토리에 README 템플릿 올리기

**Comment by SeungrokYoon** [comment]
![image](https://github.com/wanted-pre-onboarding-team-12th-7/pre-onboarding-12th-2-7/assets/44149596/c2b0cf5c-00ee-425d-a710-9ec7ff722bbe)
