### ISSUE TITLE
Theme Provider 리팩토링

### ISSUE THREAD

**Issue by JangHyunjeong** [wanted-pre-onboarding-team-12th-7/pre-onboarding-12th-2-7#25]
# TODO
- [ ] 스타일 상수들 themeProvider 에 옮기기
- [ ] 스타일 파일에 변경사항 적용
- [ ] ThemeProvider 타입 추론 추가

---------------

              이렇게 컬러 하나하나 넣는 것도 좋지만, 아예 colors를 넣는 건 어떨까요 ?!

```
export const Theme: DefaultTheme ={
  colors
}
```

이렇게 하면 밖에서는 ${({ theme }) => theme.colors.~~}로 사용하면 되고,
colors가 아닌 flex나 fontSize도 넣어서 theme으로 함께 사용할 수 있을 것 같아요 !

_Originally posted by @wisdomin121 in https://github.com/wanted-pre-onboarding-team-12th-7/pre-onboarding-12th-2-7/pull/24#discussion_r1311661162_
