### ISSUE TITLE
이슈 상세 페이지 제작하기

### ISSUE THREAD

**Issue by wisdomin121** [wanted-pre-onboarding-team-12th-7/pre-onboarding-12th-2-7#5]
## Todo
- [x] 상세 페이지 UI
- [x] 상세 페이지 데이터 로드
- [x] 리스트에서 상세 페이지 연결
